TATB-05-BUG-Add-login-link-to-user-registration-form-login-form-compo…
Jyoti-Technosoft/technical-assistant pull request #27
Opened 2023-03-21 13:25 UTC by PrabhatJTDeveloper

…nent

2023-03-21 13:37 UTC, charmijtdev requested changes

2023-03-21 13:37 UTC, charmijtdev commented on src/app/authorization/registration/registration.component.html
> +                formControlName="birthday"
Can you please change controller name ?

2023-03-21 13:37 UTC, charmijtdev commented on src/app/authorization/registration/registration.component.scss
> +input[type="date"] {
Please use class instead

2023-03-21 13:37 UTC, charmijtdev commented on src/app/authorization/registration/registration.component.scss
> +.form {
Why form class direct ?

2023-03-21 13:37 UTC, charmijtdev commented on src/app/authorization/registration/registration.component.scss
> +.field {
Please change to diffrent class name

2023-03-21 13:37 UTC, charmijtdev commented on src/app/authorization/registration/registration.component.ts
> +
Remove white space

2023-03-21 13:37 UTC, charmijtdev commented on src/app/authorization/registration/registration.component.ts
> +  registerUser: any = [];
please change any type as already declared as array

2023-03-21 13:37 UTC, charmijtdev commented on src/app/authorization/registration/registration.component.ts
> +  };
Please add space here

2023-03-21 13:37 UTC, charmijtdev commented on src/app/authorization/registration/registration.component.ts
>    }
Please add space here

2023-03-22 06:25 UTC, charmijtdev requested changes

2023-03-22 06:25 UTC, charmijtdev commented on src/app/authorization/registration/registration.component.html
> +              id="acceptTerms"
what is use for id here ?

2023-03-22 06:25 UTC, charmijtdev commented on src/app/authorization/registration/registration.component.html
>              <div
I guess no  need for this pleaser remove this

2023-03-22 06:25 UTC, charmijtdev commented on src/app/authorization/registration/registration.component.ts
> +  getRegistredUser() {
please add space here and remove condition for below to match

2023-03-22 09:11 UTC, charmijtdev approved these changes

2023-03-22 09:14 UTC, PoojanPatelJT approved these changes

2023-03-22 09:28 UTC, closed without merging