TATB - 39 [BUG]: Wrap Dialog Data into one config object for more readability
Jyoti-Technosoft/technical-assistant pull request #46
Opened 2023-03-25 10:39 UTC by PrabhatJTDeveloper

2023-03-25 12:01 UTC, charmijtdev requested changes

2023-03-25 12:01 UTC, charmijtdev commented on src/app/authorization/login/login.component.ts
> +      this.userData = JSON.parse(data);
could you please change this to JSON.parse(localstore.getitem('register user')as string)

2023-03-25 12:01 UTC, charmijtdev commented on src/app/component/header/header.component.html
> +      style="margin: 0px"
why inline css

2023-03-25 12:01 UTC, charmijtdev commented on src/app/component/header/header.component.html
> +      href="#"
no need for href tag

2023-03-25 12:01 UTC, charmijtdev commented on src/app/component/header/header.component.html
> +        width="35"
why width height on same please change to external css

2023-03-25 12:01 UTC, charmijtdev commented on src/app/component/header/header.component.html
> +          <img src="assets/img/logo1.png" alt="" class="img-responsive" />
please provide alt here

2023-03-25 12:01 UTC, charmijtdev commented on src/app/component/header/header.component.html
> +              style="color: rgb(116, 116, 116)"
why inline css please change this

2023-03-25 12:01 UTC, charmijtdev commented on src/app/component/header/header.component.html
> +              style="min-width: auto; border: none"
why inline css ?

2023-03-25 12:01 UTC, charmijtdev commented on src/app/component/header/header.component.ts
> +      (data: any) => data?.id
why removed condtiion ? how i can get the specified user ?

2023-03-25 12:01 UTC, charmijtdev commented on src/app/component/header/header.component.ts
> +          if (value) {
wht is use for value here ?

2023-03-25 12:01 UTC, charmijtdev commented on src/app/dialog-service/dialog.service.ts
> +
please remove this empty space and remove comma after NgbModal

2023-03-25 12:01 UTC, charmijtdev commented on src/app/dialog-service/modal/modal/modal.component.html
> +<!-- <div class="container-fluid">
please remove this commented code

2023-03-25 12:01 UTC, charmijtdev commented on src/app/dialog-service/modal/modal/modal.component.html
> +</div>
do code formatting

2023-03-25 13:04 UTC, PrabhatJTDeveloper commented on src/app/authorization/login/login.component.ts
> +      this.userData = JSON.parse(data);
yes, i changed it.

2023-03-25 13:05 UTC, PrabhatJTDeveloper commented on src/app/component/header/header.component.html
> +      style="margin: 0px"
yes, i removed it

2023-03-25 13:05 UTC, PrabhatJTDeveloper commented on src/app/component/header/header.component.html
> +      href="#"
ok, i removed it.

2023-03-25 13:05 UTC, PrabhatJTDeveloper commented on src/app/component/header/header.component.html
> +        width="35"
yes. i removed it.

2023-03-25 13:06 UTC, PrabhatJTDeveloper commented on src/app/component/header/header.component.html
> +          <img src="assets/img/logo1.png" alt="" class="img-responsive" />
ok, i changed it.

2023-03-25 13:06 UTC, PrabhatJTDeveloper commented on src/app/component/header/header.component.html
> +              style="color: rgb(116, 116, 116)"
ok, i changed it.

2023-03-25 13:06 UTC, PrabhatJTDeveloper commented on src/app/component/header/header.component.html
> +              style="min-width: auto; border: none"
i removed it.

2023-03-25 13:07 UTC, PrabhatJTDeveloper commented on src/app/component/header/header.component.ts
> +      (data: any) => data?.id
yes, i added it.

2023-03-25 13:07 UTC, PrabhatJTDeveloper commented on src/app/component/header/header.component.ts
> +          if (value) {
there is no use for it so i removed it.

2023-03-25 13:08 UTC, PrabhatJTDeveloper commented on src/app/dialog-service/dialog.service.ts
> +
yes, i removed it.

2023-03-25 13:08 UTC, PrabhatJTDeveloper commented on src/app/dialog-service/modal/modal/modal.component.html
> +<!-- <div class="container-fluid">
yes, i removed it.

2023-03-25 13:09 UTC, PrabhatJTDeveloper commented on src/app/dialog-service/modal/modal/modal.component.html
> +</div>
yes, i have done this.

2023-03-27 04:55 UTC, charmijtdev requested changes

2023-03-27 04:55 UTC, charmijtdev commented on src/app/authorization/login/login.component.ts
> +  styleUrls: ['./login.component.scss'],
please remove comma

2023-03-27 04:55 UTC, charmijtdev commented on src/app/component/header/header.component.html
> +  style="padding: 0px"
please remove inline styling

2023-03-27 04:55 UTC, charmijtdev commented on src/app/component/header/header.component.ts
> +  styleUrls: ['./header.component.scss'],
please remove comma

2023-03-27 04:55 UTC, charmijtdev commented on src/app/component/header/header.component.ts
> +  about() {
change function name to openAboutDialog()

2023-03-27 12:03 UTC, charmijtdev approved these changes

2023-03-27 12:03 UTC, merged